### PR TITLE
Fixed an indent

### PR DESCRIPTION
**Pull request by miiiiiYT**
Fixed #205

### CODE REVIEW

**Comment by miiiiiYT** [comment]
Please wait before merging/closing, I'm onto resolving the conflict

**Comment by miiiiiYT** [comment]
OK, the issue seems like something with the indents again. Unfortunately, I can't do much about this, so just overwrite it.

**Comment by rajkumardusad** [comment]
Hey @miiiiiYT there is some conflict.

**Comment by miiiiiYT** [comment]
Yeah, I know, but as I said, it should be safe, to just overwrite it.

It should say "Resolve conflict" or something like that and in this case you could e.g. delete your code and then just merge mine. The functionality is the same. The problem/conflict is the change in the tabs/indents.

**Comment by rajkumardusad** [comment]
Sorry i can't resolve it manually.

**Comment by miiiiiYT** [comment]
But I can't resolve it either because I don't have write access. Either you can resolve it or just delete your menu.py and copy mine into it. They are the same files, I just commented two lines or so out.

@rajkumardusad

**Comment by miiiiiYT** [comment]
Like, most of the issues of this repo are this exact issue. And just saying to install the modules with pip can't help, because it gets installed with the tool itself.

One thing you could do is rewrite the entire installation mechanism, so that you use requests instead of `os.sys` with wget.

**Pull request closed without merging**
