### PR TITLE
Revert "No connection fix"

### PR DESCRIPTION
**Pull request by miiiiiYT**
Reverts rajkumardusad/Tool-X#219

@rajkumardusad Sorry to bother u again, but there is an indentaition error in the code, isn't it?

### CODE REVIEW

**Comment by rajkumardusad** [comment]
Tere are some indentation error's and thats not a proper solution for not network connection error.
In Tool-X when we install some tools, tool-x check your network connection and then run the installation process. But you have removed that network connection validation code. that's no a solution.

**Comment by Rustycodplayer** [comment]
im having an issue 
Capture

**Comment by rajkumardusad** [comment]
> im having an issue
> Capture

We will fix this issue soon, you can try our new [onex](https://github.com/rajkumardusad/onex) that is better than this one.

**Comment by rajkumardusad** [comment]
You can not fix this issue. are you trying it on linux?

**Comment by Rustycodplayer** [comment]
I’m trying it on a Kali Linux app first I had to install windows subsystem for Linux on the windows features app

**Comment by Rustycodplayer** [comment]
I’m installing linux on my laptop to see if it will work

**Comment by rajkumardusad** [comment]
This tool is not for windows subsystem it only for linux, but we will try to fix this issue.

**Comment by Rustycodplayer** [comment]
The windows subsystem allows me to install the kernel of Linux on my pc and use the Linux dystro to install and hack stuff like tool x but not working ;(

**Comment by rajkumardusad** [comment]
You can try onex.

**Comment by Rustycodplayer** [comment]
can u send direct download link

**Comment by rajkumardusad** [comment]
https://github.com/rajkumardusad/onex

**Comment by Rustycodplayer** [comment]
thx

**Comment by Rustycodplayer** [comment]
my laptop is having graphical issues i never had issues before install linux mint its having graphical issues

**Comment by Rustycodplayer** [comment]
Capture

**Comment by Rustycodplayer** [comment]
another issue

**Comment by Rustycodplayer** [comment]
hello are u there

**Comment by Rustycodplayer** [comment]
i got tool x to work on my laptop aka linux mint how do i use the tools when i install them

**Comment by Rustycodplayer** [comment]
hm

**Comment by miiiiiYT** [comment]
@rajkumardusad 

I know, late reply but I wanted to make something clear. The way this network check and the way the installation process is written, makes it so, that it fails really often. Generally speaking, you do not need to check for an internet connection, because if the installation command fails, then you already know there was no connection. However, using os.system to get files is really inefficient and not the smartest, because you cannot easily get to the stdout of the command. It would be better to use the requests module you are even importing, but that never gets used. But in general, the network check is not needed, and the way it checks for a connection, makes it really easy to fail, even if there is a connection.

Have a great day.

**Comment by rajkumardusad** [comment]
> @rajkumardusad
> 
> I know, late reply but I wanted to make something clear. The way this network check and the way the installation process is written, makes it so, that it fails really often. Generally speaking, you do not need to check for an internet connection, because if the installation command fails, then you already know there was no connection. However, using os.system to get files is really inefficient and not the smartest, because you cannot easily get to the stdout of the command. It would be better to use the requests module you are even importing, but that never gets used. But in general, the network check is not needed, and the way it checks for a connection, makes it really easy to fail, even if there is a connection.
> 
> Have a great day.

I have used requests for network connection checking. we are check the network connection before every tool installation. so how can we improve it?

**Pull request closed without merging**
